#!/bin/bash
# Probe Palm Beach County school subdomains
# Pattern: {initials-of-meaningful-words}{level-abbrev}.palmbeachschools.org
# level: es=elementary, ms=middle, hs=high, k8=k-8
# e.g., "Bear Lakes Middle" → bl+ms = blms.palmbeachschools.org

BASE="palmbeachschools.org"

check() {
  local slug="$1"
  local name="$2"
  code=$(curl -s "https://${slug}.${BASE}" -L --max-time 2 -o /dev/null -w "%{http_code}" 2>/dev/null)
  if [ "$code" = "200" ]; then
    echo "FOUND|${slug}.${BASE}|${name}"
  fi
}

# Batch 1: A-C schools
check "apes" "Acreage Pines Elementary"
check "ames" "Addison Mizner School"
check "dsoa" "Alexander Dreyfoos School of Arts"
check "a1es" "Allamanda Elementary"
check "ahs" "Atlantic High School"
check "bams" "Bak Middle School of Arts"
check "bces" "Banyan Creek Elementary"
check "btes" "Barton Elementary"
check "bcis" "Beacon Cove Intermediate"
check "blms" "Bear Lakes Middle"
check "bges" "Belle Glade Elementary"
check "bves" "Belvedere Elementary"
check "bfes" "Benoist Farms Elementary"
check "bkes" "Berkshire Elementary"
check "bies" "Binks Forest Elementary"
check "brhs" "Boca Raton Community High"
check "brms" "Boca Raton Community Middle"
check "bres" "Boca Raton Elementary"
check "bbhs" "Boynton Beach Community High"
check "cale" "Calusa Elementary"
check "cvms" "Carver Middle"
check "cles" "Cholee Lake Elementary"
check "cmms" "Christa McAuliffe Middle"
check "cces" "Citrus Cove Elementary"
check "cotes" "Clifford Taylor Elementary"
check "ccms" "Congress Community Middle"
check "crms" "Conniston Middle"
check "cres" "Coral Reef Elementary"
check "cses" "Coral Sunset Elementary"
check "cwms" "Crestwood Community Middle"
check "cpes" "Crosspointe Elementary"
check "cles2" "Crystal Lakes Elementary"
check "ctes" "Cypress Trails Elementary"

# Batch 2: D-G schools
check "dpes" "Del Prado Elementary"
check "dves" "Diamond View Elementary"
check "dkes" "Discovery Key Elementary"
check "dehms" "Don Estridge High Tech Middle"
check "dees" "Dr Mary McLeod Bethune Elementary"
check "deis" "Dwight Eisenhower Elementary"
check "elms" "Eagles Landing Middle"
check "eles" "Egret Lake Elementary"
check "emes" "Elbridge Gale Elementary"
check "ecms" "Emerald Cove Middle"
check "etes" "Equestrian Trails Elementary"
check "ees" "Everglades Elementary"
check "fhhs" "Forest Hill Community High"
check "fhes" "Forest Hill Elementary"
check "fpes" "Forest Park Elementary"
check "fses" "Freedom Shores Elementary"
check "fres" "Frontier Elementary"
check "gaes" "Galaxy Elementary"
check "gves" "Glade View Elementary"
check "gchs" "Glades Central High"
check "gges" "Golden Grove Elementary"
check "goes" "Gove Elementary"
check "gwes" "Grassy Waters Elementary"
check "gaes2" "Greenacres Elementary"
check "gpes" "Grove Park Elementary"

# Batch 3: H-M schools
check "hljes" "H L Johnson Elementary"
check "hres" "Hammock Pointe Elementary"
check "htes" "Heritage Elementary"
check "hpms" "Highland Park Middle"
check "hles" "Hope Centennial Elementary"
check "ipes" "Inlet Grove Community High"
check "jfkes" "J F Kennedy Middle"
check "jhs" "Jupiter High"
check "jefs" "Jupiter Elementary"
check "jfes" "Jerry Thomas Elementary"
check "jhms" "Jupiter Middle"
check "jves" "Jupiter Farms Elementary"
check "kes" "Kaya Academy"
check "lges" "Lake Shore Middle"
check "lwhs" "Lake Worth High"
check "lwms" "Lake Worth Middle"
check "lwes" "Lake Worth Elementary"
check "lses" "Lake Shore Elementary"
check "laes" "Lantana Elementary"
check "lams" "Lantana Middle"
check "lhes" "Liberty Park Elementary"
check "lwcms" "Lake Worth Community Middle"
check "mmes" "Morikami Park Elementary"
check "mpes" "Melaleuca Elementary"
check "mvms" "Mariemont Elementary"

# Batch 4: N-Z schools
check "nbmes" "North Grade Elementary"
check "nles" "North Grade Elementary"
check "obes" "Odyssey Middle"
check "pbch" "Palm Beach Central High"
check "pbhhs" "Palm Beach Lakes High"
check "pbes" "Palm Beach Public Elementary"
check "pbshs" "Palm Beach Gardens High"
check "pbgms" "Palm Beach Gardens Middle"
check "pbgchs" "Palm Beach Gardens Community High"
check "pgchs" "Palm Beach Gardens Community High"
check "pmsm" "Pahokee Middle High"
check "ptes" "Palmetto Elementary"
check "rhes" "Rolling Green Elementary"
check "rves" "Royal Palm Beach Elementary"
check "rpbhs" "Royal Palm Beach High"
check "rpbms" "Royal Palm Beach Middle"
check "saes" "Santaluces Community High"
check "slhs" "Santaluces High"
check "skms" "Seminole Trails Elementary"
check "smes" "South Olive Elementary"
check "soes" "South Olive Elementary"
check "sges" "Starlight Cove Elementary"
check "stms" "Sunrise Park Elementary"
check "sves" "Sunrise Park Elementary"
check "tes" "Timber Trace Elementary"
check "tms" "Tradewinds Middle"
check "wbhs" "Wellington High"
check "wchs" "Westpine Middle"
check "wles" "West Boynton Elementary"
check "wtes" "Wynnebrook Elementary"

echo "Done"
