import { PrismaClient } from "../src/generated/prisma";
import { PrismaNeon } from "@prisma/adapter-neon";
import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(__dirname, "../.env.local") });

const adapter = new PrismaNeon({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter } as never);

const districts = [
  {
    name: "Miami-Dade County Public Schools",
    ncesId: "1200870",
    city: "Miami",
    county: "Miami-Dade",
    website: "https://www.dadeschools.net",
    schoolCount: 454,
  },
  {
    name: "Broward County Public Schools",
    ncesId: "1200420",
    city: "Fort Lauderdale",
    county: "Broward",
    website: "https://www.browardschools.com",
    schoolCount: 241,
  },
  {
    name: "Palm Beach County School District",
    ncesId: "1201380",
    city: "West Palm Beach",
    county: "Palm Beach",
    website: "https://www.palmbeachschools.org",
    schoolCount: 186,
  },
  {
    name: "Orange County Public Schools",
    ncesId: "1201290",
    city: "Orlando",
    county: "Orange",
    website: "https://www.ocps.net",
    schoolCount: 200,
  },
  {
    name: "Hillsborough County Public Schools",
    ncesId: "1200690",
    city: "Tampa",
    county: "Hillsborough",
    website: "https://www.sdhc.k12.fl.us",
    schoolCount: 262,
  },
];

const schools = [
  // Miami-Dade
  {
    name: "Coral Gables Senior High School",
    ncesId: "120087000001",
    city: "Coral Gables",
    county: "Miami-Dade",
    address: "450 Bird Rd",
    zipCode: "33146",
    phone: "(305) 445-7731",
    website: "https://coralgablescavaliers.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2890,
    districtIdx: 0,
  },
  {
    name: "Coconut Grove Elementary School",
    ncesId: "120087000002",
    city: "Coconut Grove",
    county: "Miami-Dade",
    address: "3351 Matilda St",
    zipCode: "33133",
    phone: "(305) 444-7386",
    website: "https://cocogroveelementary.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "K-5",
    studentCount: 612,
    districtIdx: 0,
  },
  {
    name: "MAST Academy",
    ncesId: "120087000003",
    city: "Miami",
    county: "Miami-Dade",
    address: "3979 NW S River Dr",
    zipCode: "33142",
    phone: "(305) 634-8899",
    website: "https://mastacademy.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "6-12",
    studentCount: 1150,
    districtIdx: 0,
  },
  {
    name: "Citrus Grove Elementary School",
    ncesId: "120087000004",
    city: "Miami",
    county: "Miami-Dade",
    address: "5301 NW 16th Ave",
    zipCode: "33142",
    phone: "(305) 634-2871",
    website: "https://citrusgroveelementary.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "K-5",
    studentCount: 524,
    districtIdx: 0,
  },
  {
    name: "Design and Architecture Senior High",
    ncesId: "120087000005",
    city: "Miami",
    county: "Miami-Dade",
    address: "4001 NE 2nd Ave",
    zipCode: "33137",
    phone: "(305) 573-8840",
    website: "https://dashs.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 780,
    districtIdx: 0,
  },
  {
    name: "Pinecrest Academy Charter School",
    ncesId: "120087000006",
    city: "Pinecrest",
    county: "Miami-Dade",
    address: "10250 SW 56th St",
    zipCode: "33165",
    phone: "(305) 382-0073",
    website: "https://pinecrestacademy.net",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 890,
    districtIdx: 0,
  },
  {
    name: "Somerset Academy Charter High",
    ncesId: "120087000007",
    city: "Miami",
    county: "Miami-Dade",
    address: "8455 W Flagler St",
    zipCode: "33144",
    phone: "(305) 553-5338",
    website: "https://somersetacademy.com",
    schoolType: "CHARTER" as const,
    gradeRange: "9-12",
    studentCount: 620,
    districtIdx: 0,
  },
  {
    name: "Aventura City of Excellence School",
    ncesId: "120087000008",
    city: "Aventura",
    county: "Miami-Dade",
    address: "3333 NE 188th St",
    zipCode: "33180",
    phone: "(305) 466-4799",
    website: "https://aces.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 740,
    districtIdx: 0,
  },
  {
    name: "Miami Norland Senior High School",
    ncesId: "120087000009",
    city: "Miami",
    county: "Miami-Dade",
    address: "1020 NW 194th St",
    zipCode: "33169",
    phone: "(305) 652-1620",
    website: "https://norlandseniorhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1680,
    districtIdx: 0,
  },
  {
    name: "Dr. Michael M. Krop Senior High School",
    ncesId: "120087000010",
    city: "Miami",
    county: "Miami-Dade",
    address: "1410 NE 215th St",
    zipCode: "33179",
    phone: "(305) 651-3834",
    website: "https://krophigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2100,
    districtIdx: 0,
  },

  // Broward
  {
    name: "Fort Lauderdale High School",
    ncesId: "120042000001",
    city: "Fort Lauderdale",
    county: "Broward",
    address: "1600 NE 4th Ave",
    zipCode: "33304",
    phone: "(754) 322-1850",
    website: "https://flhs.browardschools.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1820,
    districtIdx: 1,
  },
  {
    name: "Coconut Creek Elementary School",
    ncesId: "120042000002",
    city: "Coconut Creek",
    county: "Broward",
    address: "4575 Lyons Rd",
    zipCode: "33073",
    phone: "(754) 322-7650",
    website: "https://coconutcreekelem.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "K-5",
    studentCount: 590,
    districtIdx: 1,
  },
  {
    name: "Deerfield Beach High School",
    ncesId: "120042000003",
    city: "Deerfield Beach",
    county: "Broward",
    address: "910 SW 15th St",
    zipCode: "33441",
    phone: "(754) 322-6650",
    website: "https://deerfieldbeachhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2240,
    districtIdx: 1,
  },
  {
    name: "Broward Community Charter School",
    ncesId: "120042000004",
    city: "Coral Springs",
    county: "Broward",
    address: "5700 NW 99th Ave",
    zipCode: "33076",
    phone: "(954) 755-8900",
    website: "https://bccschool.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 480,
    districtIdx: 1,
  },
  {
    name: "Hollywood Hills High School",
    ncesId: "120042000005",
    city: "Hollywood",
    county: "Broward",
    address: "5400 Stirling Rd",
    zipCode: "33021",
    phone: "(754) 323-1100",
    website: "https://hollywoodhillshigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1650,
    districtIdx: 1,
  },
  {
    name: "Imagine Charter School at Broward",
    ncesId: "120042000006",
    city: "Plantation",
    county: "Broward",
    address: "1400 N Pine Island Rd",
    zipCode: "33322",
    phone: "(954) 382-5010",
    website: "https://imagineschools.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 560,
    districtIdx: 1,
  },
  {
    name: "Coral Springs Middle School",
    ncesId: "120042000007",
    city: "Coral Springs",
    county: "Broward",
    address: "2251 NW 102nd Way",
    zipCode: "33065",
    phone: "(754) 322-6450",
    website: "https://coralspringsmiddle.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "6-8",
    studentCount: 1120,
    districtIdx: 1,
  },
  {
    name: "Miramar High School",
    ncesId: "120042000008",
    city: "Miramar",
    county: "Broward",
    address: "3601 SW 89th Ave",
    zipCode: "33025",
    phone: "(754) 323-1200",
    website: "https://miramarhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2450,
    districtIdx: 1,
  },
  {
    name: "Parkway Middle School",
    ncesId: "120042000009",
    city: "Lauderhill",
    county: "Broward",
    address: "1100 NW 55th Ave",
    zipCode: "33313",
    phone: "(754) 322-7350",
    website: "https://parkwaymiddle.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "6-8",
    studentCount: 980,
    districtIdx: 1,
  },
  {
    name: "Ben Gamla Charter School",
    ncesId: "120042000010",
    city: "Hollywood",
    county: "Broward",
    address: "2751 N 29th Ave",
    zipCode: "33020",
    phone: "(954) 967-4400",
    website: "https://bengamla.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 670,
    districtIdx: 1,
  },

  // Palm Beach
  {
    name: "Palm Beach Lakes High School",
    ncesId: "120138000001",
    city: "West Palm Beach",
    county: "Palm Beach",
    address: "3505 Shiloh Dr",
    zipCode: "33407",
    phone: "(561) 640-5100",
    website: "https://pblakelets.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1980,
    districtIdx: 2,
  },
  {
    name: "Boca Raton Community High School",
    ncesId: "120138000002",
    city: "Boca Raton",
    county: "Palm Beach",
    address: "1501 NW 15th Ct",
    zipCode: "33486",
    phone: "(561) 338-1600",
    website: "https://bocahigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2350,
    districtIdx: 2,
  },
  {
    name: "Don Estridge High Tech Middle School",
    ncesId: "120138000003",
    city: "Boca Raton",
    county: "Palm Beach",
    address: "5200 NW 2nd Ave",
    zipCode: "33487",
    phone: "(561) 241-2420",
    website: "https://donestridge.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "6-8",
    studentCount: 1340,
    districtIdx: 2,
  },
  {
    name: "Inlet Grove Community High School",
    ncesId: "120138000004",
    city: "Riviera Beach",
    county: "Palm Beach",
    address: "750 W Blue Heron Blvd",
    zipCode: "33404",
    phone: "(561) 340-4800",
    website: "https://inletgrove.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1120,
    districtIdx: 2,
  },
  {
    name: "Palm Beach Charter School",
    ncesId: "120138000005",
    city: "Lake Worth",
    county: "Palm Beach",
    address: "1901 N Dixie Hwy",
    zipCode: "33460",
    phone: "(561) 641-8200",
    website: "https://pbcharter.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 510,
    districtIdx: 2,
  },
  {
    name: "Jupiter High School",
    ncesId: "120138000006",
    city: "Jupiter",
    county: "Palm Beach",
    address: "500 N Military Trail",
    zipCode: "33458",
    phone: "(561) 744-4400",
    website: "https://jupiterhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2680,
    districtIdx: 2,
  },
  {
    name: "Wellington High School",
    ncesId: "120138000007",
    city: "Wellington",
    county: "Palm Beach",
    address: "2101 Greenview Shores Blvd",
    zipCode: "33414",
    phone: "(561) 753-3950",
    website: "https://wellingtonhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2140,
    districtIdx: 2,
  },
  {
    name: "Glades Day School",
    ncesId: "120138000008",
    city: "Belle Glade",
    county: "Palm Beach",
    address: "400 School Rd",
    zipCode: "33430",
    phone: "(561) 996-6769",
    website: "https://gladesday.com",
    schoolType: "PRIVATE" as const,
    gradeRange: "K-12",
    studentCount: 320,
    districtIdx: 2,
  },
  {
    name: "Suncoast Community High School",
    ncesId: "120138000009",
    city: "Riviera Beach",
    county: "Palm Beach",
    address: "1300 W Blue Heron Blvd",
    zipCode: "33404",
    phone: "(561) 882-3600",
    website: "https://suncoasthigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1560,
    districtIdx: 2,
  },
  {
    name: "Quantum House Charter School",
    ncesId: "120138000010",
    city: "West Palm Beach",
    county: "Palm Beach",
    address: "3300 S Australian Ave",
    zipCode: "33405",
    phone: "(561) 659-7400",
    website: "https://quantumhouse.org",
    schoolType: "CHARTER" as const,
    gradeRange: "K-5",
    studentCount: 280,
    districtIdx: 2,
  },

  // Orange County
  {
    name: "Dr. Phillips High School",
    ncesId: "120129000001",
    city: "Orlando",
    county: "Orange",
    address: "6500 Turkey Lake Rd",
    zipCode: "32819",
    phone: "(407) 354-2000",
    website: "https://drphillipshigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 3100,
    districtIdx: 3,
  },
  {
    name: "Winter Park High School",
    ncesId: "120129000002",
    city: "Winter Park",
    county: "Orange",
    address: "2100 Summerfield Rd",
    zipCode: "32792",
    phone: "(407) 622-3200",
    website: "https://winterparkhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2860,
    districtIdx: 3,
  },
  {
    name: "Lake Nona High School",
    ncesId: "120129000003",
    city: "Orlando",
    county: "Orange",
    address: "12500 Narcoossee Rd",
    zipCode: "32832",
    phone: "(407) 207-3700",
    website: "https://lakenonahigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2240,
    districtIdx: 3,
  },
  {
    name: "Apopka High School",
    ncesId: "120129000004",
    city: "Apopka",
    county: "Orange",
    address: "555 Martin St",
    zipCode: "32703",
    phone: "(407) 703-3800",
    website: "https://apopkahigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2780,
    districtIdx: 3,
  },
  {
    name: "Orlando Science Charter School",
    ncesId: "120129000005",
    city: "Orlando",
    county: "Orange",
    address: "700 N Econlockhatchee Trail",
    zipCode: "32825",
    phone: "(407) 208-8655",
    website: "https://orlandoscience.org",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 820,
    districtIdx: 3,
  },
  {
    name: "Cornerstone Charter Academy",
    ncesId: "120129000006",
    city: "Kissimmee",
    county: "Orange",
    address: "1901 W Carroll St",
    zipCode: "34741",
    phone: "(407) 870-4343",
    website: "https://cornerstonecharter.net",
    schoolType: "CHARTER" as const,
    gradeRange: "K-12",
    studentCount: 1100,
    districtIdx: 3,
  },
  {
    name: "Edgewater High School",
    ncesId: "120129000007",
    city: "Orlando",
    county: "Orange",
    address: "3100 Edgewater Dr",
    zipCode: "32804",
    phone: "(407) 835-4400",
    website: "https://edgewaterhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1920,
    districtIdx: 3,
  },
  {
    name: "Evans High School",
    ncesId: "120129000008",
    city: "Orlando",
    county: "Orange",
    address: "4949 Silver Star Rd",
    zipCode: "32808",
    phone: "(407) 297-9700",
    website: "https://evanshigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2050,
    districtIdx: 3,
  },
  {
    name: "Freedom High School",
    ncesId: "120129000009",
    city: "Orlando",
    county: "Orange",
    address: "2500 Woodbury Rd",
    zipCode: "32828",
    phone: "(407) 482-8600",
    website: "https://freedomhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2340,
    districtIdx: 3,
  },
  {
    name: "Innovations Middle School of Technology",
    ncesId: "120129000010",
    city: "Orlando",
    county: "Orange",
    address: "13200 Daryl Carter Pkwy",
    zipCode: "32836",
    phone: "(407) 905-3200",
    website: "https://innovationsmiddle.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "6-8",
    studentCount: 1080,
    districtIdx: 3,
  },

  // Hillsborough
  {
    name: "Tampa Bay Technical High School",
    ncesId: "120069000001",
    city: "Tampa",
    county: "Hillsborough",
    address: "6410 Orient Rd",
    zipCode: "33610",
    phone: "(813) 744-8988",
    website: "https://tampatech.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1280,
    districtIdx: 4,
  },
  {
    name: "Plant High School",
    ncesId: "120069000002",
    city: "Tampa",
    county: "Hillsborough",
    address: "2415 S Himes Ave",
    zipCode: "33629",
    phone: "(813) 272-3007",
    website: "https://planthigh.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2950,
    districtIdx: 4,
  },
  {
    name: "Hillsborough High School",
    ncesId: "120069000003",
    city: "Tampa",
    county: "Hillsborough",
    address: "5000 N Central Ave",
    zipCode: "33603",
    phone: "(813) 272-3007",
    website: "https://hillsboroughhigh.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1750,
    districtIdx: 4,
  },
  {
    name: "Blake High School",
    ncesId: "120069000004",
    city: "Tampa",
    county: "Hillsborough",
    address: "1701 N Alexander St",
    zipCode: "33605",
    phone: "(813) 272-3000",
    website: "https://blakehigh.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 1420,
    districtIdx: 4,
  },
  {
    name: "Jesuit High School Tampa",
    ncesId: "120069000005",
    city: "Tampa",
    county: "Hillsborough",
    address: "4701 N Himes Ave",
    zipCode: "33614",
    phone: "(813) 877-5344",
    website: "https://jesuittampa.org",
    schoolType: "PRIVATE" as const,
    gradeRange: "9-12",
    studentCount: 870,
    districtIdx: 4,
  },
  {
    name: "Academy at the Farm Charter School",
    ncesId: "120069000006",
    city: "Lithia",
    county: "Hillsborough",
    address: "16302 Fishhawk Blvd",
    zipCode: "33547",
    phone: "(813) 633-3551",
    website: "https://academyatthefarm.com",
    schoolType: "CHARTER" as const,
    gradeRange: "K-8",
    studentCount: 690,
    districtIdx: 4,
  },
  {
    name: "Chamberlain High School",
    ncesId: "120069000007",
    city: "Tampa",
    county: "Hillsborough",
    address: "9401 N Boulevard",
    zipCode: "33612",
    phone: "(813) 975-7350",
    website: "https://chamberlain.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2110,
    districtIdx: 4,
  },
  {
    name: "Freedom High School Hillsborough",
    ncesId: "120069000008",
    city: "Tampa",
    county: "Hillsborough",
    address: "14326 Mansel Rd",
    zipCode: "33629",
    phone: "(813) 671-5100",
    website: "https://freedomhillsborough.com",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2420,
    districtIdx: 4,
  },
  {
    name: "Wharton High School",
    ncesId: "120069000009",
    city: "Tampa",
    county: "Hillsborough",
    address: "20150 Bruce B Downs Blvd",
    zipCode: "33647",
    phone: "(813) 631-4710",
    website: "https://whartonhigh.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2870,
    districtIdx: 4,
  },
  {
    name: "Gaither High School",
    ncesId: "120069000010",
    city: "Tampa",
    county: "Hillsborough",
    address: "16200 N Dale Mabry Hwy",
    zipCode: "33618",
    phone: "(813) 975-7550",
    website: "https://gaitherhigh.mysdhc.org",
    schoolType: "PUBLIC" as const,
    gradeRange: "9-12",
    studentCount: 2650,
    districtIdx: 4,
  },
];

async function main() {
  console.log("🌱 Seeding Florida K-12 schools...");

  // Create districts
  const createdDistricts = [];
  for (const d of districts) {
    const district = await prisma.district.upsert({
      where: { ncesId: d.ncesId },
      update: d,
      create: { ...d, state: "FL" },
    });
    createdDistricts.push(district);
    console.log(`✅ District: ${district.name}`);
  }

  // Create schools
  let schoolCount = 0;
  for (const s of schools) {
    const { districtIdx, ...schoolData } = s;
    const district = createdDistricts[districtIdx];
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    await (prisma.school.upsert as any)({
      where: { ncesId: schoolData.ncesId },
      update: { ...schoolData, districtId: district?.id ?? null },
      create: { ...schoolData, districtId: district?.id ?? null },
    });
    schoolCount++;
  }
  console.log(`✅ Seeded ${schoolCount} schools across ${createdDistricts.length} districts`);
  console.log("🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
